version: '3'

services:
  db:
    image: mariadb
    env_file:
      - db.env
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

  nextcloud:
    image: nextcloud
    depends_on:
      - db
    links:
      - db
    env_file:
      - db.env
    environment:
      MYSQL_HOST: db
      NEXTCLOUD_ADMIN_USER: ${ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - nextcloud:/var/www/html
      - ${DATA_PATH}/nextcloud:/var/www/html/data
      - ${DATA_PATH}/aria2:/aria2
      - ${RO_DATA_PATH}:/ro-data:ro
    restart: unless-stopped

  aria2:
    image: xujinkai/aria2-with-webui
    ports:
      - 6800:6800
    environment:
      - SECRET=${RPC_SECRET}
    volumes:
      - ${DATA_PATH}/aria2:/data
    restart: unless-stopped

  proxy:
    image: abiosoft/caddy
    links:
      - nextcloud
      - aria2
    ports:
      - 3080:80
    environment:
      - SERVER=:80
      - CADDYPATH=/etc/caddycerts
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - caddycerts:/etc/caddycerts
    restart: unless-stopped

volumes:
  db:
  nextcloud:
  caddycerts:
