version: '3'

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_DATABASE: filerun
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

  filerun:
    image: afian/filerun
    depends_on:
      - db
    links:
      - db
    volumes:
      - filerun-html:/var/www/html
      - ${USER_FILES}:/user-files
    restart: unless-stopped

  aria2:
    image: xujinkai/aria2-with-webui
    ports:
      - 6800:6800
    environment:
      - SECRET=${RPC_SECRET}
    volumes:
      - ${USER_FILES}/aria2:/data

  proxy:
    image: abiosoft/caddy
    links:
      - filerun
      - aria2
    ports:
      - 3080:80
    environment:
      - SERVER=:80
      - CADDYPATH=/etc/caddycerts
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - caddycerts:/etc/caddycerts

volumes:
  db:
  filerun-html:
  caddycerts:
